language: node_js
node_js: "stable"
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y bash coreutils grep make procps sed
  - sudo apt-get install -y curl git python xsltproc
install: npm install jison -g
script: ./configure && make build
